# Generated by Django 4.2.10 on 2024-02-27 19:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reachapp', '0003_platformengagementtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('target_followers_count', models.PositiveIntegerField()),
                ('achieved_follower_count', models.PositiveIntegerField(default=0)),
                ('credits_required', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reachapp.platformengagementtype')),
                ('social_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reachapp.socialprofile')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
