# Generated by Django 4.2.10 on 2024-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachapp', '0004_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='credits_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
