# Generated by Django 4.2.10 on 2024-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachapp', '0005_alter_promotion_credits_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
