# Generated by Django 4.2.10 on 2024-02-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachapp', '0007_platformengagementtype_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='link',
            field=models.URLField(blank=True, help_text='link of post', null=True),
        ),
    ]
