# Generated by Django 4.2.10 on 2024-03-03 18:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reachapp', '0008_promotion_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_given', to='reachapp.socialprofile')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reachapp.promotion')),
            ],
            options={
                'unique_together': {('promoter', 'promotion')},
            },
        ),
    ]
